### Pandas
Pandas is an open-source Python library designed for data manipulation and analysis, particularly for handling structured, tabular data similar to spreadsheets or SQL tables. 

In Pandas, the two fundamental data structures are Series and DataFrame, which serve as the building blocks for data manipulation and analysis. 

Series is a one-dimensional, labeled array-like object that can hold any data type (integers, strings, floats, etc.).  It consists of a single column of data with an associated index, functioning similarly to a NumPy array but with explicit labels for each element. Series elements are typically homogeneous, and it supports element-wise computations. 

DataFrame is a two-dimensional, tabular data structure consisting of rows and columns.  It can be viewed as a collection of multiple Series objects or a spreadsheet/SQL table. Unlike Series, DataFrames are heterogeneous, meaning different columns can contain different data types (e.g., numbers, strings, dates).  They support more complex operations, including column-wise computations, alignment, and multi-variable data handling.

In [3]:
!pip install numpy

Requirement already satisfied: numpy in /media/oxv3geta/Work/python for Ml/venv/lib/python3.13/site-packages (2.4.5)

In [2]:
## Series
## A pandas Seres is a one-demensional array-like object that can hold any data type.It is similar to a column in a table.

import pandas as pd
data = [3,4,5,1,2]
series = pd.Series(data)
print("Series\n",series)
print(type(series))

Series
 0    3
1    4
2    5
3    1
4    2
dtype: int64
<class 'pandas.Series'>

In [ ]:
## create a series of from dictionary
data = {'a':1,'b':4,'c':8}
series_dict = pd.Series(data)

print(series_dict)

a    1
b    4
c    8
dtype: int64

In [34]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [ ]:
## Dataframe
# create a dataframe from a dictionary of list

data = {
    'name':['Goku','Vegeta','Gohan'],
    'age' :[42,47,22],
    'planet':['Planet Vegeta','Sadala','Earth']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

     name  age         planet
0    Goku   42  Planet Vegeta
1  Vegeta   47         Sadala
2   Gohan   22          Earth
<class 'pandas.DataFrame'>

In [38]:
## create a Data frame from list of dictionary

data2 = [
    {'name':'Goku','age' :42,'planet':'Planet Vegeta'},
    {'name':'Vegeta','age' :47,'planet':'salada'},
    {'name':'Gohan','age' :22,'planet':'Earth'},
    {'name':'Piccolo','age' :35,'planet':'namek'}
]
df_2 = pd.DataFrame(data2)
print(df_2)
print(type(df_2))

      name  age         planet
0     Goku   42  Planet Vegeta
1   Vegeta   47         salada
2    Gohan   22          Earth
3  Piccolo   35          namek
<class 'pandas.DataFrame'>

In [ ]:
df_car = pd.read_csv('used_cars.csv')
df_car.head(5)

In [ ]:
df.tail(5)

In [41]:
### Accessing data form dataframe
df

     name  age         planet
0    Goku   42  Planet Vegeta
1  Vegeta   47         Sadala
2   Gohan   22          Earth

In [45]:
df['name']

0      Goku
1    Vegeta
2     Gohan
Name: name, dtype: str

In [46]:
type(df['name'])

pandas.Series

In [55]:
df.loc[0] ## loc for row index,in there we use [0] row index

name               Goku
age                  42
planet    Planet Vegeta
Name: 0, dtype: object

In [11]:
df.iloc[1] ## iloc for index location

name      Vegeta
age           47
planet    Sadala
Name: 1, dtype: object

In [ ]:
df

     name  age         planet
0    Goku   42  Planet Vegeta
1  Vegeta   47         Sadala
2   Gohan   22          Earth

In [63]:
## Accessing a specified element 
df.at[0,'name']

'Goku'

In [8]:
df.at[0,'planet']

'Planet Vegeta'

In [10]:
## Accessing specific element using iat 
df.iat[2,2]

'Earth'

In [ ]:
## Data manupulation with dataframe
df

     name  age         planet
0    Goku   42  Planet Vegeta
1  Vegeta   47         Sadala
2   Gohan   22          Earth

In [17]:
## Adding a column
df["Power"] = [999,970,800]
df

     name  age         planet  Power
0    Goku   42  Planet Vegeta    999
1  Vegeta   47         Sadala    970
2   Gohan   22          Earth    800

In [21]:
## Remove a column
df.drop("Power",axis = 1,inplace=True)

In [22]:
df

     name  age         planet
0    Goku   42  Planet Vegeta
1  Vegeta   47         Sadala
2   Gohan   22          Earth

In [87]:
## Add age

df['age'] =df['age']+1
df

     name  age         planet
0    Goku   44  Planet Vegeta
1  Vegeta   49         Sadala
2   Gohan   24          Earth

In [25]:
df.drop(0)

     name  age  planet
1  Vegeta   47  Sadala
2   Gohan   22   Earth

In [93]:
df_car = pd.read_csv("used_cars.csv")
df_car.head(5)

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [97]:
## Display the data type of each column
print("Data type:\n",df_car.dtypes)

## Describe the Dataframe
print("Statistical summary:\n",df_car.describe)

Data type:
 brand             str
model             str
model_year      int64
milage            str
fuel_type         str
engine            str
transmission      str
ext_col           str
int_col           str
accident          str
clean_title       str
price             str
dtype: object
Statistical summary:
 <bound method NDFrame.describe of          brand                            model  model_year      milage  \
0         Ford  Utility Police Interceptor Base        2013  51,000 mi.
1      Hyundai                     Palisade SEL        2021  34,742 mi.
2        Lexus                    RX 350 RX 350        2022  22,372 mi.
3     INFINITI                 Q50 Hybrid Sport        2015  88,900 mi.
4         Audi        Q3 45 S line Premium Plus        2021   9,835 mi.
...        ...                              ...         ...         ...
4004   Bentley             Continental GT Speed        2023     714 mi.
4005      Audi             S4 3.0T Premium Plus        2022  10,900 mi.
4006   Porsche                           Taycan        2022   2,116 mi.
4007      Ford                     F-150 Raptor        2020  33,000 mi.
4008       BMW                     X3 xDrive30i        2020  43,000 mi.

          fuel_type                                             engine  \
0     E85 Flex Fuel  300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...
1          Gasoline                               3.8L V6 24V GDI DOHC
2          Gasoline                                     3.5 Liter DOHC
3            Hybrid  354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...
4          Gasoline                         2.0L I4 16V GDI DOHC Turbo
...             ...                                                ...
4004       Gasoline                   6.0L W12 48V PDI DOHC Twin Turbo
4005       Gasoline      349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel
4006            NaN                                           Electric
4007       Gasoline      450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel
4008       Gasoline       248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel

                           transmission                 ext_col  int_col  \
0                           6-Speed A/T                   Black    Black
1                     8-Speed Automatic         Moonlight Cloud     Gray
2                             Automatic                    Blue    Black
3                           7-Speed A/T                   Black    Black
4                     8-Speed Automatic  Glacier White Metallic    Black
...                                 ...                     ...      ...
4004  8-Speed Automatic with Auto-Shift                   C / C  Hotspur
4005     Transmission w/Dual Shift Mode                   Black    Black
4006                          Automatic                   Black    Black
4007                                A/T                    Blue    Black
4008                                A/T                    Gray    Brown

                                    accident clean_title     price
0     At least 1 accident or damage reported         Yes   $10,300
1     At least 1 accident or damage reported         Yes   $38,005
2                              None reported         NaN   $54,598
3                              None reported         Yes   $15,500
4                              None reported         NaN   $34,999
...                                      ...         ...       ...
4004                           None reported         Yes  $349,950
4005                           None reported         Yes   $53,900
4006                           None reported         NaN   $90,998
4007                           None reported         Yes   $62,999
4008  At least 1 accident or damage reported         Yes   $40,000

[4009 rows x 12 columns]>

In [98]:
df_car.describe()

        model_year
count  4009.000000
mean   2015.515590
std       6.104816
min    1974.000000
25%    2012.000000
50%    2017.000000
75%    2020.000000
max    2024.000000