In [6]:
import numpy as np

arr_1 =np.array([1,2,3,4,5,6])
print(arr_1)
print(type(arr_1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>

In [8]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

In [1]:
import pandas as pd

data = [1,2,3,4,5,6,6,7]

series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
5    6
6    6
7    7
dtype: int64

In [2]:
data = {'a':1,'b':4,'c':6,'d':21}
series = pd.Series(data)
print(series)

a     1
b     4
c     6
d    21
dtype: int64

In [4]:
data = [10,20,30]
index = ['a','b','c']

pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [6]:
data = {
    'name':['Goku','Vegeta','Gohan'],
    'age' :[42,47,22],
    'planet':['Planet Vegeta','Sadala','Earth']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

     name  age         planet
0    Goku   42  Planet Vegeta
1  Vegeta   47         Sadala
2   Gohan   22          Earth
<class 'pandas.DataFrame'>

In [7]:
df_car = pd.read_csv('used_cars.csv')
df_car.head(5)

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [9]:
df.tail(5)

     name  age         planet
0    Goku   42  Planet Vegeta
1  Vegeta   47         Sadala
2   Gohan   22          Earth

In [11]:
df['name']

0      Goku
1    Vegeta
2     Gohan
Name: name, dtype: str

In [12]:
type(df['name'])

pandas.Series

In [17]:
df.loc[0]

name               Goku
age                  42
planet    Planet Vegeta
Name: 0, dtype: object

In [18]:
df.iloc[0]

name               Goku
age                  42
planet    Planet Vegeta
Name: 0, dtype: object

In [20]:
df['age'] =df['age']+1
df

     name  age         planet
0    Goku   44  Planet Vegeta
1  Vegeta   49         Sadala
2   Gohan   24          Earth

In [21]:
print("Data type:\n",df_car.dtypes)

Data type:
 brand             str
model             str
model_year      int64
milage            str
fuel_type         str
engine            str
transmission      str
ext_col           str
int_col           str
accident          str
clean_title       str
price             str
dtype: object

In [24]:
print("Statiscal summery:\n",df_car.describe)

Statiscal summery:
 <bound method NDFrame.describe of          brand                            model  model_year      milage  \
0         Ford  Utility Police Interceptor Base        2013  51,000 mi.
1      Hyundai                     Palisade SEL        2021  34,742 mi.
2        Lexus                    RX 350 RX 350        2022  22,372 mi.
3     INFINITI                 Q50 Hybrid Sport        2015  88,900 mi.
4         Audi        Q3 45 S line Premium Plus        2021   9,835 mi.
...        ...                              ...         ...         ...
4004   Bentley             Continental GT Speed        2023     714 mi.
4005      Audi             S4 3.0T Premium Plus        2022  10,900 mi.
4006   Porsche                           Taycan        2022   2,116 mi.
4007      Ford                     F-150 Raptor        2020  33,000 mi.
4008       BMW                     X3 xDrive30i        2020  43,000 mi.

          fuel_type                                             engine  \
0     E85 Flex Fuel  300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...
1          Gasoline                               3.8L V6 24V GDI DOHC
2          Gasoline                                     3.5 Liter DOHC
3            Hybrid  354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...
4          Gasoline                         2.0L I4 16V GDI DOHC Turbo
...             ...                                                ...
4004       Gasoline                   6.0L W12 48V PDI DOHC Twin Turbo
4005       Gasoline      349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel
4006            NaN                                           Electric
4007       Gasoline      450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel
4008       Gasoline       248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel

                           transmission                 ext_col  int_col  \
0                           6-Speed A/T                   Black    Black
1                     8-Speed Automatic         Moonlight Cloud     Gray
2                             Automatic                    Blue    Black
3                           7-Speed A/T                   Black    Black
4                     8-Speed Automatic  Glacier White Metallic    Black
...                                 ...                     ...      ...
4004  8-Speed Automatic with Auto-Shift                   C / C  Hotspur
4005     Transmission w/Dual Shift Mode                   Black    Black
4006                          Automatic                   Black    Black
4007                                A/T                    Blue    Black
4008                                A/T                    Gray    Brown

                                    accident clean_title     price
0     At least 1 accident or damage reported         Yes   $10,300
1     At least 1 accident or damage reported         Yes   $38,005
2                              None reported         NaN   $54,598
3                              None reported         Yes   $15,500
4                              None reported         NaN   $34,999
...                                      ...         ...       ...
4004                           None reported         Yes  $349,950
4005                           None reported         Yes   $53,900
4006                           None reported         NaN   $90,998
4007                           None reported         Yes   $62,999
4008  At least 1 accident or damage reported         Yes   $40,000

[4009 rows x 12 columns]>

In [25]:
df_car.describe()

        model_year
count  4009.000000
mean   2015.515590
std       6.104816
min    1974.000000
25%    2012.000000
50%    2017.000000
75%    2020.000000
max    2024.000000

In [40]:
df = pd.read_csv('Chocolate_Sales.csv')
df.head(10)

,Order_ID,Product,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.7
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69
5,ORD-051262,70% Dark Bar,Brazil,Online,Lucas Walker,2023-08-04,17.8,12.87,76.94,47,527.01
6,ORD-041587,Hazelnut Milk Bar,Australia,Wholesale,Ananya Gupta,2023-02-20,12.0,3.18,241.18,159,470.63
7,ORD-017541,Mixed Assortment Box,Australia,Online,Lucas Walker,2022-04-01,22.6,2.43,94.27,326,629.51
8,ORD-134320,85% Dark Bar,Germany,Retail,Rohan Patel,2022-08-26,13.9,2.98,68.88,70,181.16
9,ORD-068442,Truffle Gift Box,Germany,Retail,Priya Sharma,2022-01-01,16.3,3.13,102.50,213,588.18

In [33]:
df.isnull().any(axis=1)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [34]:
df.tail(5)

,Order_ID,Product,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount
5,ORD-051262,70% Dark Bar,Brazil,Online,Lucas Walker,2023-08-04,17.8,12.87,76.94,47,527.01
6,ORD-041587,Hazelnut Milk Bar,Australia,Wholesale,Ananya Gupta,2023-02-20,12.0,3.18,241.18,159,470.63
7,ORD-017541,Mixed Assortment Box,Australia,Online,Lucas Walker,2022-04-01,22.6,2.43,94.27,326,629.51
8,ORD-134320,85% Dark Bar,Germany,Retail,Rohan Patel,2022-08-26,13.9,2.98,68.88,70,181.16
9,ORD-068442,Truffle Gift Box,Germany,Retail,Priya Sharma,2022-01-01,16.3,3.13,102.50,213,588.18

In [36]:
df.describe()

       Discount_Pct  Price_per_Box  Marketing_Spend  Boxes_Shipped
count     10.000000      10.000000        10.000000      10.000000
mean      11.980000       6.523000       114.107000     131.100000
std        6.362005       5.964774        69.440741      94.130465
min        3.500000       2.430000        52.000000      35.000000
25%        6.025000       2.807500        62.707500      70.250000
50%       12.950000       3.155000        85.605000      88.000000
75%       15.975000      10.477500       166.205000     199.500000
max       22.600000      18.210000       241.180000     326.000000

In [49]:
df.isnull().sum()

Order_ID             0
Product              0
Country              0
Channel              0
Salesperson          0
Order_Date         437
Discount_Pct       489
Price_per_Box      457
Marketing_Spend    461
Boxes_Shipped        0
Amount               0
dtype: int64

In [48]:
df_filled = df.fillna(2)

In [52]:
df.isnull().sum()

Order_ID             0
Product              0
Country              0
Channel              0
Salesperson          0
Order_Date         437
Discount_Pct       489
Price_per_Box      457
Marketing_Spend    461
Boxes_Shipped        0
Amount               0
dtype: int64

In [54]:
df

,Order_ID,Product,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.7
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69
...,...,...,...,...,...,...,...,...,...,...,...
199995,ORD-053460,70% Dark Bar,Australia,Retail,Beatriz Souza,2022-05-27,10.6,3.39,186.19,125,418.56
199996,ORD-010743,Truffle Gift Box,India,Wholesale,Arjun Mehta,2022-09-06,17.3,3.07,42.28,148,366.47
199997,ORD-049690,Salted Caramel Bar,Japan,Online,Arjun Mehta,2022-06-16,18.3,2.74,100.19,149,329.79
199998,ORD-189637,85% Dark Bar,Japan,Wholesale,Rohan Patel,2022-10-14,9.3,14.30,29.96,24,304.51
199999,ORD-061616,Mint Dark Bar,Australia,Retail,Hannah Müller,2022-01-25,7.2,3.01,270.86,131,366.91

In [55]:
df['Price_per_Box_NA'] = df['Price_per_Box'].fillna(df['Price_per_Box'].mean())
df.head()

,Order_ID,Product,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount,Price_per_Box_NA
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31,13.72
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91,3.30
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.7,18.21
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27,2.66
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69,2.75

In [56]:
df.dtypes

Order_ID                str
Product                 str
Country                 str
Channel                 str
Salesperson             str
Order_Date              str
Discount_Pct        float64
Price_per_Box       float64
Marketing_Spend     float64
Boxes_Shipped         int64
Amount                  str
Price_per_Box_NA    float64
dtype: object

In [57]:
df = df.rename(columns={'Product':'Product_Name'})

In [59]:
df

,Order_ID,Product_Name,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount,Price_per_Box_NA
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31,13.72
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91,3.30
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.7,18.21
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27,2.66
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69,2.75
...,...,...,...,...,...,...,...,...,...,...,...,...
199995,ORD-053460,70% Dark Bar,Australia,Retail,Beatriz Souza,2022-05-27,10.6,3.39,186.19,125,418.56,3.39
199996,ORD-010743,Truffle Gift Box,India,Wholesale,Arjun Mehta,2022-09-06,17.3,3.07,42.28,148,366.47,3.07
199997,ORD-049690,Salted Caramel Bar,Japan,Online,Arjun Mehta,2022-06-16,18.3,2.74,100.19,149,329.79,2.74
199998,ORD-189637,85% Dark Bar,Japan,Wholesale,Rohan Patel,2022-10-14,9.3,14.30,29.96,24,304.51,14.30
199999,ORD-061616,Mint Dark Bar,Australia,Retail,Hannah Müller,2022-01-25,7.2,3.01,270.86,131,366.91,3.01

In [60]:
df['Discount_Pct_new'] = df['Discount_Pct'].fillna(df['Discount_Pct'].mean()).astype(int)
df.head(5)

,Order_ID,Product_Name,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount,Price_per_Box_NA,Discount_Pct_new
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31,13.72,3
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91,3.30,9
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.7,18.21,4
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27,2.66,15
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69,2.75,4

In [61]:
df['Discount_Pct_new'] = df['Discount_Pct'].apply(lambda x:x*2)
df

,Order_ID,Product_Name,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount,Price_per_Box_NA,Discount_Pct_new
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31,13.72,7.0
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91,3.30,18.8
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.7,18.21,9.8
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27,2.66,30.0
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69,2.75,8.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,ORD-053460,70% Dark Bar,Australia,Retail,Beatriz Souza,2022-05-27,10.6,3.39,186.19,125,418.56,3.39,21.2
199996,ORD-010743,Truffle Gift Box,India,Wholesale,Arjun Mehta,2022-09-06,17.3,3.07,42.28,148,366.47,3.07,34.6
199997,ORD-049690,Salted Caramel Bar,Japan,Online,Arjun Mehta,2022-06-16,18.3,2.74,100.19,149,329.79,2.74,36.6
199998,ORD-189637,85% Dark Bar,Japan,Wholesale,Rohan Patel,2022-10-14,9.3,14.30,29.96,24,304.51,14.30,18.6
199999,ORD-061616,Mint Dark Bar,Australia,Retail,Hannah Müller,2022-01-25,7.2,3.01,270.86,131,366.91,3.01,14.4

In [62]:
df.head(5)

,Order_ID,Product_Name,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount,Price_per_Box_NA,Discount_Pct_new
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31,13.72,7.0
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91,3.30,18.8
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.7,18.21,9.8
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27,2.66,30.0
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69,2.75,8.8